version: "2"
services:
  app:
    build: ./fastapi
    links:
      - db
      - nginx-proxy
    ports:
      - "8000:8000"
    depends_on:
      - db
      - nginx-proxy
    networks:
      - mynet
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=WOM

  engine:
    build: ./engine
    links:
      - db
      - nginx-proxy
    ports:
      - "8001:8001"
    depends_on:
      - db
      - nginx-proxy
    networks:
      - mynet

  db:
    build: ./db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - mynet
  
  nginx-proxy:
    build: ./proxy
    ports:
      - "8081:8081"
    networks:
      - mynet

  front:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: node
    ports:
      - "81:80"
    networks:
      - mynet

networks:
  mynet: