version: "2"
services:
  app:
    build: ./fastapi
    links:
      - db
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mynet
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=WOM

  db:
    build: ./db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=VOM
    networks:
      - mynet


networks:
  mynet: